title: GreenIT Community
description: La communauté Awesome Numérique Responsable
theme: just-the-docs
color_scheme: dark

url: https://greenit.community

aux_links:
  "Awesome Numérique Responsable sur GitHub":
    - "//github.com/greenit-community/awesome-numerique-responsable"
  "GreenIT Community sur GitHub":
    - "//github.com/greenit-community/greenit-community.github.io"
